language: java

install:
    - wget https://github.com/SKCraft/Launcher/archive/master.zip
    - unzip master.zip
    - sudo chmod +x $(which gradle)
    - ./Launcher-master/gradlew clean build

script:
    - java -jar ./Launcher-master/launcher-builder/build/libs/launcher-builder-*.jar \
      --version TRAVIS_BUILD_NUMBER \
      --input .
      --output build
      --manifest-dest "build/lfg_modpack.json"
