language: java
jdk:
- oraclejdk8
sudo: false
addons:
  artifacts:
    working_dir: build
  apt:
    packages:
    - oracle-java8-installer
install:
- wget https://github.com/SKCraft/Launcher/archive/master.zip
- unzip master.zip
- cd ./Launcher-master
- chmod +x ./build.sh
- "./gradlew clean build"
- cd -
script:
- java -jar ./Launcher-master/launcher-builder/build/libs/launcher-builder-4.3-SNAPSHOT-all.jar
  --version "$(echo TRAVIS_BUILD_NUMBER)" --input "./LFG Project Ozone 2" --output
  build --manifest-dest "build/lfg_modpack.json"
before_install:
- openssl aes-256-cbc -K $encrypted_64a7da176b6f_key -iv $encrypted_64a7da176b6f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
