language: java
jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
    - wget https://github.com/SKCraft/Launcher/archive/master.zip
    - unzip master.zip
    - cd ./Launcher-master
    - chmod +x ./build.sh
    - ./gradlew clean build
    - cd -

script:
    - java -jar ./Launcher-master/launcher-builder/build/libs/launcher-builder-*.jar \
      --version TRAVIS_BUILD_NUMBER \
      --input "./LFG Project Ozone 2"
      --output build
      --manifest-dest "build/lfg_modpack.json"
