language: java
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
  ssh_known_hosts: revanchist.lfgame.rs
install:
- wget https://github.com/SKCraft/Launcher/archive/master.zip
- unzip master.zip
- cd ./Launcher-master
- chmod +x ./build.sh
- "./gradlew clean build"
- cd -
script:
- java -jar ./Launcher-master/launcher-builder/build/libs/launcher-builder-4.3-SNAPSHOT-all.jar
  --version "$TRAVIS_BUILD_NUMBER" --input "./LFG Project Ozone 2" --output build
  --manifest-dest "build/lfg_modpack.json"
- zip -r upload.zip build
before_script:
- openssl aes-256-cbc -K $encrypted_c738aac456cd_key -iv $encrypted_c738aac456cd_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: scp upload.zip modpack@revanchist.lfgame.rs:/var/www/modpack
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: ssh modpack@revanchist.lfgame.rs "cd /var/www/modpack && rm -fr pack &&
    unzip upload.zip && mv build pack && rm upload.zip"
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: NJW3NyZYPllo2GQvSg5lTSFsjSjU9xtCkWwMp/8D/I2O4vasqdAjz2tXctvYqcdJuWNHHIsHxVQk38yok0+INErnMPBNBGnRTb3phsPyMcF1Co+rrFisoOVB6aMToPzRglE9/aRs5sJiJ+//FfDpQh6acmrNIWLW1uV4UJxAnOtZTypRq6lEB1Ui5LXh8fWscTdg7B4OesysXSRPsotYvfzbpipIczBdszAuIBijbzLp/Tuwhhw52DU0jxpfd9lhvFSQbjysrMqXXDid0qQAv1yVklihck6KgTYu9JQlZxsmb6PONX5FU9zaKn+oJU9iuUaK8fvcJYF4qJT24urA3wGQFydx1/X4lkA4YB/+T0bK+ou0hmcYhyklECB7uNMoKSplauULDFpZe08hVQ2cywkgu8C/Jl800XmK7VyNYiS9FHA7fuJIiMgG6Nhs7G9FPCFkyAPSFOG54RYSb3+0/QtvV4bt9W7HXkaI3Bv3cm9rIZ1j6KmrpVV6PrND6i8r89EcnUpF6Er+VhqWidCofSFEBjRIe8eTW1RvwdsZcH0Eoc2WyLijdQQ0/8iq0cENxrEmwkrCfyFR8mQAUG6jZCj70jEqD9CuWKoszvP4jafqq8Bgvv8dm/8lMnYxlBUoVqI7q7srhotomJeUcKDdeZXqBPhcbWUOzFrlYr9YckY=
